version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: attendance_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: attendance_db
      MYSQL_USER: attendance_user
      MYSQL_PASSWORD: attendance_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    image: php:7.4-apache  # Imagen oficial de PHP con Apache
    container_name: attendance_php
    volumes:
      - ./attendance-app:/var/www/html    # Monte tu código en el contenedor
    ports:
      - "8080:80"                         # Exponer el puerto 8080
    depends_on:
      - db                                # Asegura que db se inicie antes de php

volumes:
  db_data:
